### ISSUE TITLE
support the actual binary representation of wkb

### ISSUE THREAD

**Issue by lovasoa** [bosth/plpygis#1]
Thank you for this useful library.

Currently, in order to get the actual wkb representation of an object, one has to do:

```py
bytes.fromhex(geo.wkb)
```

It would be both more efficient and more intuitive if `geo.wkb` contained directly the Well-Known **Binary** representation of the geometry. The string representation of the wkb could still be obtained with : 

```py
geo.wkb.hex()
```

What do you think about this change ? Would you be opened to a pull request ?

**Comment by bosth** [comment]
Hi, I'm open to a PR. Just be aware that `__str__` has to return a string so that PL/Python correctly converts to a PostGIS `geometry` type.
