### ISSUE TITLE
Pointarray length (2061584302) is too large making MultiPolygonZ

### ISSUE THREAD

**Issue by disarticulate** [bosth/plpygis#10]
Trying to convert some polygons into multipolygons and return as part of a function table.

getting ```Pointarray length (2061584302) is too large``` The number changes based on what is getting passed in. The wkb I get is:

```01060000a03d9501001600000001030000a00100000005000000ae47e17ad4a4b040dd24068115f7a9401283c0ca21129440ae47e17ad4a4b040dd24068115f7a9401283c0ca21fe9340ae47e17a3476b04066666666a60baa4046b6f3fdd4fc9340ae47e17a3476b04066666666a60baa4046b6f3fdd4109440ae47e17ad4a4b040dd24068115f7a9401283c0ca2112944001030000a00100000005000000dd240681951db1408195438b2c98a9402b8716d9ce0d9440dd240681951db1408195438b2c98a9402b8716d9cef9934004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87fc934004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87109440dd240681951db1408195438b2c98a9402b8716d9ce0d944001030000a00100000005000000ae47e17a3476b04066666666a60baa4046b6f3fdd4109440ae47e17a3476b04066666666a60baa4046b6f3fdd4fc9340ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0cafb9340ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0ca0f9440ae47e17a3476b04066666666a60baa4046b6f3fdd410944001030000a0010000000500000004560e2df2dfb040f0a7c64bf7d1a9404a0c022b8710944004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87fc9340ae47e17ad4a4b040dd24068115f7a9401283c0ca21fe9340ae47e17ad4a4b040dd24068115f7a9401283c0ca2112944004560e2df2dfb040f0a7c64bf7d1a9404a0c022b8710944001030000a00100000005000000ac1c5a641b6fb1409eefa7c68b37a9404260e5d022059440ac1c5a641b6fb1409eefa7c68b37a9404260e5d022f19340dd240681951db1408195438b2c98a9402b8716d9cef99340dd240681951db1408195438b2c98a9402b8716d9ce0d9440ac1c5a641b6fb1409eefa7c68b37a9404260e5d02205944001030000a00100000005000000068195432ba6b0401d5a643b9ffea9401283c0ca21129440068195438b77b040a69bc4203013aa4046b6f3fdd4109440068195438b77b040a69bc4203013aa4046b6f3fdd4fc9340068195432ba6b0401d5a643b9ffea9401283c0ca21fe9340068195432ba6b0401d5a643b9ffea9401283c0ca2112944001030000a00100000005000000355eba49ec1eb140c1caa145b69fa9402b8716d9ce0d9440a8c64b3749e1b0402fdd240681d9a9404a0c022b87109440a8c64b3749e1b0402fdd240681d9a9404a0c022b87fc9340355eba49ec1eb140c1caa145b69fa9402b8716d9cef99340355eba49ec1eb140c1caa145b69fa9402b8716d9ce0d944001030000a00100000005000000068195438b77b040a69bc4203013aa4046b6f3fdd410944091ed7c3ff53db040fed478e9262caa406f1283c0ca0f944091ed7c3ff53db040fed478e9262caa406f1283c0cafb9340068195438b77b040a69bc4203013aa4046b6f3fdd4fc9340068195438b77b040a69bc4203013aa4046b6f3fdd410944001030000a00100000005000000a8c64b3749e1b0402fdd240681d9a9404a0c022b87109440068195432ba6b0401d5a643b9ffea9401283c0ca21129440068195432ba6b0401d5a643b9ffea9401283c0ca21fe9340a8c64b3749e1b0402fdd240681d9a9404a0c022b87fc9340a8c64b3749e1b0402fdd240681d9a9404a0c022b8710944001030000a0010000000500000004560e2d7270b140dd240681153fa9404260e5d022059440355eba49ec1eb140c1caa145b69fa9402b8716d9ce0d9440355eba49ec1eb140c1caa145b69fa9402b8716d9cef9934004560e2d7270b140dd240681153fa9404260e5d022f1934004560e2d7270b140dd240681153fa9404260e5d02205944001030000a00100000005000000ae47e17ad4a4b040dd24068115f7a9401283c0ca21fe934004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87fc9340a8c64b3749e1b0402fdd240681d9a9404a0c022b87fc9340068195432ba6b0401d5a643b9ffea9401283c0ca21fe9340ae47e17ad4a4b040dd24068115f7a9401283c0ca21fe934001030000a00100000005000000ac1c5a641b6fb1409eefa7c68b37a9404260e5d022f19340ac1c5a641b6fb1409eefa7c68b37a9404260e5d02205944004560e2d7270b140dd240681153fa9404260e5d02205944004560e2d7270b140dd240681153fa9404260e5d022f19340ac1c5a641b6fb1409eefa7c68b37a9404260e5d022f1934001030000a00100000005000000ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0cafb9340ae47e17a3476b04066666666a60baa4046b6f3fdd4fc9340068195438b77b040a69bc4203013aa4046b6f3fdd4fc934091ed7c3ff53db040fed478e9262caa406f1283c0cafb9340ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0cafb934001030000a00100000005000000dd240681951db1408195438b2c98a9402b8716d9ce0d944004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87109440a8c64b3749e1b0402fdd240681d9a9404a0c022b87109440355eba49ec1eb140c1caa145b69fa9402b8716d9ce0d9440dd240681951db1408195438b2c98a9402b8716d9ce0d944001030000a00100000005000000ae47e17a3476b04066666666a60baa4046b6f3fdd4fc9340ae47e17ad4a4b040dd24068115f7a9401283c0ca21fe9340068195432ba6b0401d5a643b9ffea9401283c0ca21fe9340068195438b77b040a69bc4203013aa4046b6f3fdd4fc9340ae47e17a3476b04066666666a60baa4046b6f3fdd4fc934001030000a00100000005000000dd240681951db1408195438b2c98a9402b8716d9cef99340ac1c5a641b6fb1409eefa7c68b37a9404260e5d022f1934004560e2d7270b140dd240681153fa9404260e5d022f19340355eba49ec1eb140c1caa145b69fa9402b8716d9cef99340dd240681951db1408195438b2c98a9402b8716d9cef9934001030000a0010000000500000004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87109440ae47e17ad4a4b040dd24068115f7a9401283c0ca21129440068195432ba6b0401d5a643b9ffea9401283c0ca21129440a8c64b3749e1b0402fdd240681d9a9404a0c022b8710944004560e2df2dfb040f0a7c64bf7d1a9404a0c022b8710944001030000a00100000005000000ae47e17a3476b04066666666a60baa4046b6f3fdd4109440ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0ca0f944091ed7c3ff53db040fed478e9262caa406f1283c0ca0f9440068195438b77b040a69bc4203013aa4046b6f3fdd4109440ae47e17a3476b04066666666a60baa4046b6f3fdd410944001030000a0010000000500000004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87fc9340dd240681951db1408195438b2c98a9402b8716d9cef99340355eba49ec1eb140c1caa145b69fa9402b8716d9cef99340a8c64b3749e1b0402fdd240681d9a9404a0c022b87fc934004560e2df2dfb040f0a7c64bf7d1a9404a0c022b87fc934001030000a00100000005000000ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0ca0f9440ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0cafb934091ed7c3ff53db040fed478e9262caa406f1283c0cafb934091ed7c3ff53db040fed478e9262caa406f1283c0ca0f9440ee7c3f359e3cb040be9f1a2f9d24aa406f1283c0ca0f944001030000a00100000005000000ae47e17ad4a4b040dd24068115f7a9401283c0ca21129440ae47e17a3476b04066666666a60baa4046b6f3fdd4109440068195438b77b040a69bc4203013aa4046b6f3fdd4109440068195432ba6b0401d5a643b9ffea9401283c0ca21129440ae47e17ad4a4b040dd24068115f7a9401283c0ca2112944001030000a00100000005000000ac1c5a641b6fb1409eefa7c68b37a9404260e5d022059440dd240681951db1408195438b2c98a9402b8716d9ce0d9440355eba49ec1eb140c1caa145b69fa9402b8716d9ce0d944004560e2d7270b140dd240681153fa9404260e5d022059440ac1c5a641b6fb1409eefa7c68b37a9404260e5d022059440```

These are the polygon: 
```
[(4260.83, 3323.542, 1284.533), (4260.83, 3323.542, 1279.533), (4214.205, 3333.825, 1279.208), (4214.205, 3333.825, 1284.208), (4260.83, 3323.542, 1284.533)]
[(4381.584, 3276.087, 1283.452), (4381.584, 3276.087, 1278.452), (4319.946, 3304.983, 1279.132), (4319.946, 3304.983, 1284.132), (4381.584, 3276.087, 1283.452)]
[(4214.205, 3333.825, 1284.208), (4214.205, 3333.825, 1279.208), (4156.618, 3346.307, 1278.948), (4156.618, 3346.307, 1283.948), (4214.205, 3333.825, 1284.208)]
[(4319.946, 3304.983, 1284.132), (4319.946, 3304.983, 1279.132), (4260.83, 3323.542, 1279.533), (4260.83, 3323.542, 1284.533), (4319.946, 3304.983, 1284.132)]
[(4463.107, 3227.773, 1281.284), (4463.107, 3227.773, 1276.284), (4381.584, 3276.087, 1278.452), (4381.584, 3276.087, 1283.452), (4463.107, 3227.773, 1281.284)]
[(4262.169, 3327.311, 1284.533), (4215.544, 3337.594, 1284.208), (4215.544, 3337.594, 1279.208), (4262.169, 3327.311, 1279.533), (4262.169, 3327.311, 1284.533)]
[(4382.923, 3279.856, 1283.452), (4321.286, 3308.752, 1284.132), (4321.286, 3308.752, 1279.132), (4382.923, 3279.856, 1278.452), (4382.923, 3279.856, 1283.452)]
[(4215.544, 3337.594, 1284.208), (4157.958, 3350.076, 1283.948), (4157.958, 3350.076, 1278.948), (4215.544, 3337.594, 1279.208), (4215.544, 3337.594, 1284.208)]
[(4321.286, 3308.752, 1284.132), (4262.169, 3327.311, 1284.533), (4262.169, 3327.311, 1279.533), (4321.286, 3308.752, 1279.132), (4321.286, 3308.752, 1284.132)]
[(4464.446, 3231.542, 1281.284), (4382.923, 3279.856, 1283.452), (4382.923, 3279.856, 1278.452), (4464.446, 3231.542, 1276.284), (4464.446, 3231.542, 1281.284)]
[(4260.83, 3323.542, 1279.533), (4319.946, 3304.983, 1279.132), (4321.286, 3308.752, 1279.132), (4262.169, 3327.311, 1279.533), (4260.83, 3323.542, 1279.533)]
[(4463.107, 3227.773, 1276.284), (4463.107, 3227.773, 1281.284), (4464.446, 3231.542, 1281.284), (4464.446, 3231.542, 1276.284), (4463.107, 3227.773, 1276.284)]
[(4156.618, 3346.307, 1278.948), (4214.205, 3333.825, 1279.208), (4215.544, 3337.594, 1279.208), (4157.958, 3350.076, 1278.948), (4156.618, 3346.307, 1278.948)]
[(4381.584, 3276.087, 1283.452), (4319.946, 3304.983, 1284.132), (4321.286, 3308.752, 1284.132), (4382.923, 3279.856, 1283.452), (4381.584, 3276.087, 1283.452)]
[(4214.205, 3333.825, 1279.208), (4260.83, 3323.542, 1279.533), (4262.169, 3327.311, 1279.533), (4215.544, 3337.594, 1279.208), (4214.205, 3333.825, 1279.208)]
[(4381.584, 3276.087, 1278.452), (4463.107, 3227.773, 1276.284), (4464.446, 3231.542, 1276.284), (4382.923, 3279.856, 1278.452), (4381.584, 3276.087, 1278.452)]
[(4319.946, 3304.983, 1284.132), (4260.83, 3323.542, 1284.533), (4262.169, 3327.311, 1284.533), (4321.286, 3308.752, 1284.132), (4319.946, 3304.983, 1284.132)]
[(4214.205, 3333.825, 1284.208), (4156.618, 3346.307, 1283.948), (4157.958, 3350.076, 1283.948), (4215.544, 3337.594, 1284.208), (4214.205, 3333.825, 1284.208)]
[(4319.946, 3304.983, 1279.132), (4381.584, 3276.087, 1278.452), (4382.923, 3279.856, 1278.452), (4321.286, 3308.752, 1279.132), (4319.946, 3304.983, 1279.132)]
[(4156.618, 3346.307, 1283.948), (4156.618, 3346.307, 1278.948), (4157.958, 3350.076, 1278.948), (4157.958, 3350.076, 1283.948), (4156.618, 3346.307, 1283.948)]
[(4260.83, 3323.542, 1284.533), (4214.205, 3333.825, 1284.208), (4215.544, 3337.594, 1284.208), (4262.169, 3327.311, 1284.533), (4260.83, 3323.542, 1284.533)]
[(4463.107, 3227.773, 1281.284), (4381.584, 3276.087, 1283.452), (4382.923, 3279.856, 1283.452), (4464.446, 3231.542, 1281.284), (4463.107, 3227.773, 1281.284)]
```

It seems like there might be an encoding issue in the wkb turn?
```
I couldn't find a debugger for ewkb. I'll poke around.

**Comment by disarticulate** [comment]
So, looks like there's an issue with how the SRID is being encoded. I've got a ESRI SRID 103741.  Is it possible the spec itself can't handle this or is the library making some assumption about the length of an srid?

**Comment by bosth** [comment]
Thanks for the report.

The spec allows for even larger SRIDs so that shouldn't be the issue. I'll have to dig in to see if there's a bug, but could you also share the code that you used to trigger the error?

**Comment by bosth** [comment]
I am able to convert the WKB above into a `MultiPolygon` and I can take the individual coordinate lists, create `Polygon`s and then and use them to create a `MultiPolygon`.

```
wkb = '01060000a03d950100...'
geom = Geometry(wkb)

p1 = Polygon([[(4260.83, 3323.542, 1284.533),...]], srid=103741)
p2 = ...
mp = MultiPolygon([p1, p2, ...])
```

Both `mp`  and `geom` return equivalent WKBs to the original input `wkb`.

**Comment by disarticulate** [comment]
```DROP FUNCTION IF EXISTS operations._blender_object_to_rows;
CREATE OR REPLACE FUNCTION operations._blender_object_to_rows(
    filepath text,
    srid int DEFAULT 103741
)
  RETURNS TABLE (
        faces geometry(MultiPolygonZ,103741),
        file_name text
    )
  AS
$BODY$
	from plpygis import Geometry
	from plpygis.geometry import Polygon, MultiPolygon
	face = [(1,2,3),(0,0,0), (2,3,4), (1,2,3)]
	polygon = Polygon([face], dimz=True, srid=srid)
	multipolygon = MultiPolygon([polygon], dimz=True)
        plpy.notice(multipolygon.wkb)
	yield multipolygon, filepath
$BODY$
LANGUAGE plpython3u VOLATILE;

SELECT *
FROM operations._blender_object_to_rows(
    'test-model'
)
```

```
DROP FUNCTION
CREATE FUNCTION
NOTICE:  01060000a03d9501000100000001030000a00100000004000000000000000000f03f00000000000000400000000000000840000000000000000000000000000000000000000000000000000000000000004000000000000008400000000000001040000000000000f03f00000000000000400000000000000840
ERROR:  Pointarray length (1072693248) is too large
CONTEXT:  while creating return value
PL/Python function "_blender_object_to_rows"
```

PostGIS version 3.4.0
plpython3u 1.0
python 3.11

**Comment by bosth** [comment]
OK there is an issue that plpygis can create invalid EWKBs for MultiPolygons with SRIDs (probably for all multi-types as wel).

The workaround is to do the following:
```
face = [(1,2,3),(0,0,0), (2,3,4), (1,2,3)]
polygon = Polygon([face], dimz=True)
multipolygon = MultiPolygon([polygon], dimz=True, srid=srid)
```

In other words, the `Polygons` shouldn't have an SRID but the `MultiPolygon` should.

I'll need to add some better handling to prevent this from happening, add test cases and improve the documentation, but I think the above will unblock you.

**Comment by disarticulate** [comment]
Cool. Another way is to set the srid when fetching the rows which is also
acceptable as its not transforming anything. But nicer to have itvreturn

**Comment by disarticulate** [comment]
Cool, good work.
