### ISSUE TITLE
SQL Error [38000]: ERROR: ImportError: cannot import name 'Geometry'

### ISSUE THREAD

**Issue by frugardc** [bosth/plpygis#5]
When executing a function defined like below, getting 'cannot import name 'Geometry''
`CREATE OR REPLACE FUNCTION  cc_s2sphere_cell_id(pnt geometry)

RETURNS text AS

$$

import s2sphere

from plpygis import Geometry

point = Geometry(pnt)`

**Comment by frugardc** [comment]
Should be clear, I am using python 3.6.9

**Comment by frugardc** [comment]
perhaps more succinctly...  `Python 3.6.9 (default, Jul 17 2020, 12:50:27) 

[GCC 8.4.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> from plpygis import Geometry

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: cannot import name 'Geometry'

>>> import plpygis`

**Comment by bosth** [comment]
That's strange.

Am I correct in understanding that `import plpygis` does _not_ product any errors?

How did you install `plpygis`? Something other than `pip3 install plpygis`?

**Comment by frugardc** [comment]
python3 -m pip install plpygis

Correct, import plpygis produces no errors.

**Comment by bosth** [comment]
What platform is this on?

And what happens with the following?

```
import plpygis
plpygis.Geometry("0101000080000000000000000000000000000000000000000000000000")
```

**Comment by frugardc** [comment]
Turns out this is a permissions issue for the postgres user to the python
packages directory.
