### ISSUE TITLE
package contains `.pyc` files

### ISSUE THREAD

**Issue by vincentsarago** [bosth/plpygis#7]
👋 @bosth 
First thanks for this great module. We are using it in https://github.com/stac-utils/pgstac and it has been really useful. 

One thing we just noticed is that the pypi package contains the `.pyc` files which are not cross version safe and could lead to some issues. 

<img width="902" alt="Screenshot 2023-03-10 at 12 27 11 PM" src="https://user-images.githubusercontent.com/10407788/224305094-2a22d1cc-48c8-4fe9-b37c-85ba60eab8cc.png">

**Comment by bosth** [comment]
Hi @vincentsarago, glad to hear this is useful! Thanks for catching the pyc files in the package. 

I reviewed and the update to `MANIFEST.in` looks good. I'll merge and release shortly.
