### ISSUE TITLE
Clarify GPL-3 license identifier

### ISSUE THREAD

**Issue by tylere** [bosth/plpygis#9]
The [license string in setup.py](https://github.com/bosth/plpygis/blob/master/setup.py#L13) is not a valid [SPDX license](https://spdx.org/licenses/) identifier, which is noted by conda-forge (https://github.com/conda-forge/staged-recipes/pull/25663).

To make conda-forge happy, could you choose one of the following IDs?
- "GPL-3.0-only"
- "GPL-3.0-or-later"

**Comment by bosth** [comment]
Should be fixed with version just published to PyPI.
